import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

cleanupOutdatedCaches()

// Precache all assets generated by Vite
// eslint-disable-next-line no-restricted-globals
precacheAndRoute(self.__WB_MANIFEST || [])

// Runtime cache for API calls
registerRoute(
  ({ url }) => url.href.includes('http://localhost:8080/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 // 24 hours
      })
    ]
  })
)

// Background Sync
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-dose-logs') {
    event.waitUntil(
      // We will replay from the frontend directly upon re-connection as a fallback,
      // but if the browser natively triggers a sync event, we can let clients know 
      // they should trigger the replay process. Service worker itself might not have 
      // the JWT auth token easily without storing it in IDB.
      clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({ type: 'REPLAY_ACTIONS' })
        })
      })
    )
  }
})

// Web Push Notifications
self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json()
    const options = {
      body: data.body,
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      vibrate: [200, 100, 200],
      data: {
        dateOfArrival: Date.now(),
        primaryKey: '2'
      }
    }
    event.waitUntil(
      self.registration.showNotification(data.title, options)
    )
  }
})

// Notification Click Event
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      for (let i = 0; i < clientList.length; i++) {
        let client = clientList[i]
        if (client.url == '/' && 'focus' in client)
          return client.focus()
      }
      if (clients.openWindow) {
        return clients.openWindow('/')
      }
    })
  )
})
